package arifraza.adrriagit;

import android.content.DialogInterface;
import android.content.Intent;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;
import java.util.Date;
import java.util.Calendar;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class cmessage extends AppCompatActivity {

    DatabaseReference databaseReports;
    EditText editText7;
    EditText editText8;
    EditText editText11;
    Button button6;
    Button button15;

    FirebaseAuth mAuth4;



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_cmessage);
        databaseReports = FirebaseDatabase.getInstance().getReference("messages");
        setTitle("Enquiry");

        editText7 = (EditText) findViewById(R.id.editText7);
        editText8 = (EditText) findViewById(R.id.editText8);
        editText11 = (EditText) findViewById(R.id.editText11);



        mAuth4 = FirebaseAuth.getInstance();




        button6 = (Button) findViewById(R.id.button6);
        //button6.setOnClickListener(new View.OnClickListener() {
          //  @Override

        //public void onClick(View v) {

        openr34();
        button6.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                openm();
                openml2();


            }
        });






    }

    private void openml2(){

        String messagel = "";
        messagel += "\n" +"Enquiry Message";
        messagel += "\n"+"-----------------------------------------------------" ;
        messagel += "\n" ;
        messagel += "\n" ;
        messagel += "\n" +  "From :"+ editText7.getText().toString();
        messagel += "\n" + " Designation :"+  editText11.getText().toString();
        messagel += "\n" + "Question :" +editText8.getText().toString();
        messagel += "\n" ;
        messagel += "\n" ;
        messagel += "\n" +"Enquiry generated by the KMC - ADR Reporter app";
        messagel += "\n" ;
        messagel += "\n" ;
        messagel += "\n"+"-----------------------------------------------------" ;
        messagel += "\n" ;
        messagel += "\n" +"Department of Pharmacology";
        messagel += "\n" +"Kasturba Medical College,Manipal";



        Intent intent = new Intent(Intent.ACTION_SEND);
        intent.putExtra(Intent.EXTRA_EMAIL,new String[] { "adrrkmc@gmail.com" });

        intent.putExtra(Intent.EXTRA_SUBJECT, "New Enquiry Message");
        intent.putExtra(Intent.EXTRA_TEXT, messagel);

        intent.setType("message/rfc822");

        intent.setPackage("com.google.android.gm");
        startActivity(intent);
            //for(int i=0;i<600;i++)

        runOnUiThread(new Runnable() {
            @Override
            public void run() {

                if (!isFinishing()){
                    new AlertDialog.Builder(cmessage.this)
                            .setTitle("Message ")
                            .setMessage("Sent Successfully")
                            .setCancelable(false)
                            .setPositiveButton("ok", new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface dialog, int which) {
                                    // Whatever...
                                }
                            }).show();
                }
            }
        });

        editText7.setText("");
        editText8.setText("");
        editText11.setText("");



    }

    private void openm() {

        Date currentTime = Calendar.getInstance().getTime();
        String dat = currentTime.toString();

        String name = editText7.getText().toString().trim();
        String loc = editText8.getText().toString().trim();
        String con = editText11.getText().toString().trim();
        String mmsg2="(No Answered yet)";
        String rnm2="(No Answered yet)";
        String rml2="(No Answered yet)";
        String dat2="(No Answered yet)";

        final FirebaseUser user444 = mAuth4.getCurrentUser();
        String seml = user444.getEmail().toString();

        String rdd= "New!";

        if (!TextUtils.isEmpty(name)) {

            String id = databaseReports.push().getKey();

            //creating an Artist Object
            msg msg = new msg(id, name, con, loc,rdd,seml,mmsg2,rnm2,rml2,dat,dat2);

            //Saving the Artist
            databaseReports.child(id).setValue(msg);

            //setting edittext to blank again
            /*
            editText7.setText("");
            editText8.setText("");
            editText11.setText("");
*/

            //displaying a success toast
            Toast.makeText(this, "Message Sent", Toast.LENGTH_LONG).show();


        } else {
          /*

*/
            //if the value is not given displaying a toast
            Toast.makeText(this, "Please enter all info first", Toast.LENGTH_LONG).show();
        }


    }
    public void openr34() {


        final FirebaseUser user4 = mAuth4.getCurrentUser();
        editText7.setText(user4.getDisplayName().toString());



    }



    public void open7021() {
        //textView3 = (TextView) findViewById(R.id.textView3);


        Intent intent = new Intent(this, myenq.class);
        startActivity(intent);

    }


}
